# Generated by Django 3.2.23 on 2023-11-20 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0003_alter_plant_taxonomy_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField(choices=[(1, 'Hydrate'), (2, 'Moist'), (3, 'Drought')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='plants.plant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'plant', 'reaction_type')},
            },
        ),
    ]
