# Generated by Django 3.2.23 on 2023-11-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.IntegerField(choices=[(1, 'Hydrate'), (2, 'Moist'), (3, 'Dry')]),
        ),
    ]
