# Generated by Django 3.2.23 on 2023-12-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_message_contact_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
    ]
