# Generated by Django 3.2.23 on 2023-11-20 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plant_request', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('requested_children', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)])),
                ('image', models.ImageField(blank=True, default='../default_post_ecbbyj.jpg', upload_to='images/')),
                ('taxonomy_choices', models.CharField(choices=[('Araceae', 'Araceae'), ('Asteraceae', 'Asteraceae'), ('Lamiaceae', 'Lamiaceae'), ('Rosaceae', 'Rosaceae'), ('Fabaceae', 'Fabaceae'), ('Poaceae', 'Poaceae'), ('Asparagaceae', 'Asparagaceae'), ('Solanaceae', 'Solanaceae'), ('Cactaceae', 'Cactaceae'), ('Rubiaceae', 'Rubiaceae'), ('Ericaceae', 'Ericaceae'), ('Crassulaceae', 'Crassulaceae'), ('Cyperaceae', 'Cyperaceae'), ('Gesneriaceae', 'Gesneriaceae'), ('Piperaceae', 'Piperaceae'), ('Apocynaceae', 'Apocynaceae'), ('Myrtaceae', 'Myrtaceae'), ('Moraceae', 'Moraceae'), ('Liliaceae', 'Liliaceae'), ('Orchidaceae', 'Orchidaceae'), ('Rutaceae', 'Rutaceae'), ('Arecaceae', 'Arecaceae'), ('Pothos Family', 'Pothos Family'), ('Bromeliaceae', 'Bromeliaceae'), ('Marantaceae', 'Marantaceae'), ('Zamiaceae', 'Zamiaceae'), ('Araliaceae', 'Araliaceae'), ('Oleaceae', 'Oleaceae'), ('Scrophulariaceae', 'Scrophulariaceae'), ('Polypodiaceae', 'Polypodiaceae'), ('Begoniaceae', 'Begoniaceae'), ('Urticaceae', 'Urticaceae'), ('Geraniaceae', 'Geraniaceae'), ('Amaranthaceae', 'Amaranthaceae'), ('Primulaceae', 'Primulaceae'), ('Campanulaceae', 'Campanulaceae'), ('Melastomataceae', 'Melastomataceae'), ('Loranthaceae', 'Loranthaceae'), ('Oxalidaceae', 'Oxalidaceae'), ('Verbenaceae', 'Verbenaceae'), ('Hydrophyllaceae', 'Hydrophyllaceae'), ('Portulacaceae', 'Portulacaceae'), ('Cannaceae', 'Cannaceae'), ('Caryophyllaceae', 'Caryophyllaceae'), ('Aizoaceae', 'Aizoaceae'), ('Araliaceae', 'Araliaceae'), ('Euphorbiaceae', 'Euphorbiaceae'), ('Saxifragaceae', 'Saxifragaceae'), ('Thymelaeaceae', 'Thymelaeaceae'), ('Hyacinthaceae', 'Hyacinthaceae')], default=None, max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
