# Generated by Django 3.2.23 on 2023-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_rename_plant_request_plant_plant_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='taxonomy_choices',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Araceae', 'Araceae'), ('Asteraceae', 'Asteraceae'), ('Lamiaceae', 'Lamiaceae'), ('Rosaceae', 'Rosaceae'), ('Fabaceae', 'Fabaceae'), ('Poaceae', 'Poaceae'), ('Asparagaceae', 'Asparagaceae'), ('Solanaceae', 'Solanaceae'), ('Cactaceae', 'Cactaceae'), ('Rubiaceae', 'Rubiaceae'), ('Ericaceae', 'Ericaceae'), ('Crassulaceae', 'Crassulaceae'), ('Cyperaceae', 'Cyperaceae'), ('Gesneriaceae', 'Gesneriaceae'), ('Piperaceae', 'Piperaceae'), ('Apocynaceae', 'Apocynaceae'), ('Myrtaceae', 'Myrtaceae'), ('Moraceae', 'Moraceae'), ('Liliaceae', 'Liliaceae'), ('Orchidaceae', 'Orchidaceae'), ('Rutaceae', 'Rutaceae'), ('Arecaceae', 'Arecaceae'), ('Pothos Family', 'Pothos Family'), ('Bromeliaceae', 'Bromeliaceae'), ('Marantaceae', 'Marantaceae'), ('Zamiaceae', 'Zamiaceae'), ('Araliaceae', 'Araliaceae'), ('Oleaceae', 'Oleaceae'), ('Scrophulariaceae', 'Scrophulariaceae'), ('Polypodiaceae', 'Polypodiaceae'), ('Begoniaceae', 'Begoniaceae'), ('Urticaceae', 'Urticaceae'), ('Geraniaceae', 'Geraniaceae'), ('Amaranthaceae', 'Amaranthaceae'), ('Primulaceae', 'Primulaceae'), ('Campanulaceae', 'Campanulaceae'), ('Melastomataceae', 'Melastomataceae'), ('Loranthaceae', 'Loranthaceae'), ('Oxalidaceae', 'Oxalidaceae'), ('Verbenaceae', 'Verbenaceae'), ('Hydrophyllaceae', 'Hydrophyllaceae'), ('Portulacaceae', 'Portulacaceae'), ('Cannaceae', 'Cannaceae'), ('Caryophyllaceae', 'Caryophyllaceae'), ('Aizoaceae', 'Aizoaceae'), ('Araliaceae', 'Araliaceae'), ('Euphorbiaceae', 'Euphorbiaceae'), ('Saxifragaceae', 'Saxifragaceae'), ('Thymelaeaceae', 'Thymelaeaceae'), ('Hyacinthaceae', 'Hyacinthaceae')], default=None, max_length=32),
        ),
    ]
