# Generated by Django 3.2.23 on 2023-12-01 15:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plant_requested_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='../default_post_ecbbyj.jpg', max_length=255, verbose_name='image'),
        ),
    ]
