# Generated by Django 3.2.23 on 2023-12-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plant_children',
        ),
    ]
