# Generated by Django 3.2.23 on 2023-11-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_remove_plant_requested_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrequest',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_requests', to='plants.plant'),
        ),
        migrations.AlterField(
            model_name='plantrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
