# Generated by Django 3.2.23 on 2023-12-09 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant_requests', '0002_auto_20231130_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrequest',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant'),
        ),
        migrations.AlterField(
            model_name='plantrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
